/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#c3f400",
        "on-primary": "#283500",
        "on-primary-container": "#556d00",
        "secondary": "#ffb1c4",
        "secondary-container": "#ff4a8d",
        "on-secondary": "#65002e",
        "on-secondary-container": "#590028",
        "secondary-fixed": "#ffd9e1",
        "secondary-fixed-dim": "#ffb1c4",
        "tertiary": "#ffffff",
        "tertiary-container": "#acedff",
        "tertiary-fixed": "#acedff",
        "tertiary-fixed-dim": "#4cd7f6",
        "surface": "#121317",
        "surface-dim": "#121317",
        "surface-bright": "#38393e",
        "surface-container-lowest": "#0d0e12",
        "surface-container-low": "#1a1b20",
        "surface-container": "#1f1f24",
        "surface-container-high": "#292a2e",
        "surface-container-highest": "#343439",
        "on-surface": "#e3e2e8",
        "on-surface-variant": "#c4c9ac",
        "outline": "#8e9379",
        "outline-variant": "#444933",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "warning-orange": "#ff5722",
        "cyber-yellow": "#fef08a",
        "cyber-pink": "#ffb1c4",
        "cyber-orange": "#fed7aa",
        "cyber-cyan": "#acedff",
      },
      fontFamily: {
        syne: ["Syne", "sans-serif"],
        sans: ["Plus Jakarta Sans", "sans-serif"],
        display: ["Syne", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
      },
      boxShadow: {
        "brutal-sm": "2px 2px 0px #0d0e12",
        "brutal": "4px 4px 0px #0d0e12",
        "brutal-lg": "6px 6px 0px #0d0e12",
        "brutal-cyan": "4px 4px 0px #06b6d4",
        "brutal-magenta": "4px 4px 0px #ff007f",
        "brutal-lime": "4px 4px 0px #c3f400",
      }
    },
  },
  plugins: [],
};
